CREATE DATABASE db_sesi6;

USE db_sesi6;

CREATE TABLE TB_SISWA(
	 id_siswa INT PRIMARY KEY IDENTITY(1,1),
	 nis VARCHAR(10),
	 nama VARCHAR(50),
	 alamat VARCHAR(100),
	 tgl_lahir Date,
	 j_kelamin varchar(1)
);

ALTER TABLE TB_SISWA 
ALTER COLUMN j_kelamin VARCHAR(10);

SELECT ts.*, nis, ts.nama from TB_SISWA ts;


INSERT INTO TB_SISWA(NIS,NAMA,ALAMAT,TGl_LAHIR,J_KELAMIN)VALUES('10001','BEJO','SURABAYA','2010-10-06','PRIA');
INSERT INTO TB_SISWA(NIS,NAMA,ALAMAT,TGl_LAHIR,J_KELAMIN)VALUES('10002','ANI','MALANG','2010-10-06','WANITA');

SELECT NAMA, tgl_lahir FROM TB_SISWA	
WHERE NIS = '10002' AND NAMA = 'ANI';

SELECT * FROM TB_SISWA WHERE ALAMAT LIKE 'SU%';

SELECT * FROM TB_SISWA WHERE TGL_LAHIR BETWEEN '09-10-2010' AND '10-10-2010';

UPDATE TB_SISWA SET NAMA = 'BEJO SUTEDJO' WHERE NIS = '10001';

DELETE TB_SISWA WHERE NIS = '10002';



